analyzer_rules:
- unused_import
- unused_private_declaration

opt_in_rules:
- convenience_type
- empty_count
- empty_string
- fatal_error_message
- file_name
- first_where
- last_where
- modifier_order
- prohibited_interface_builder
- toggle_bool
- unused_private_declaration
- no_extension_access_modifier
- attributes
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- contains_over_first_not_nil
- discouraged_object_literal
- empty_xctest_method
- explicit_self
- fallthrough
- force_unwrapping
- function_default_parameter_at_end
- identical_operands
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- mark
- modifier_order
- multiline_arguments
- operator_usage_whitespace
- overridden_super_call
- private_action
- private_outlet
- private_over_fileprivate
- private_unit_test
- prohibited_interface_builder
- prohibited_super_call
- redundant_discardable_let
- redundant_nil_coalescing
- static_operator
- strict_fileprivate

line_length:
  warning: 300
  error: 300

type_body_length:
  warning: 1000
  error: 1000

file_length:
  warning: 1000
  error: 1000

function_body_length:
  warning: 200
  error: 200

identifier_name:
  excluded:
  - id
  - ip
  - to

nesting:
  type_level:
    warning: 2

cyclomatic_complexity:
  ignores_case_statements: true
