trigger:
- master

jobs:
- job: Code_Quality
  timeoutInMinutes: 5
  pool:
    vmImage: 'Ubuntu 16.04'
  container: norionomura/swiftlint:swift-4.2.1
  steps:
    - script: |
        set -o pipefail
        swiftlint lint --strict
      displayName: swift lint

- job: Linux_Tests
  dependsOn: Code_Quality
  timeoutInMinutes: 5
  pool:
    vmImage: 'Ubuntu-16.04'
  container: norionomura/swift:swift-4.2.1
  steps:
    - script: |
        set -o pipefail
        swift test --parallel
      displayName: swift test
