
trigger:
- master

jobs:    
- job: iOS_Tests
  pool:
   vmImage: 'macOS 10.13'
  timeoutInMinutes: 10
  strategy:
    maxParallel: 3
    matrix:
      iPhone_5s_iOS12_1:
        device: 'iPhone 5s,OS=12.1'
  steps:
  - script: swift package generate-xcodeproj
  - task: Xcode@5
    displayName: 'Xcode iOS Build'
    inputs:
      actions: 'test'
      scheme: 'Aurora-Package'
      xcWorkspacePath: 'Aurora.xcodeproj'
      sdk: 'iphonesimulator12.1'
      configuration: 'Debug'
      xcodeVersion: '10'
      packageApp: false
      destinationSimulators: $(device)
      destinationTypeOption: 'simulators'
      destinationPlatformOption: 'iOS'
      signingOption: "auto"
      useXcpretty: false
