jobs:
- job: swiftlint
  pool:
    vmImage: 'Ubuntu 16.04'
  container: norionomura/swiftlint:swift-4.2.1
  steps:
    - script: |
        set -o pipefail
        mkdir -p build/reports/
        swiftlint lint --strict --reporter junit > build/reports/swiftlint.xml
      displayName: swiftlint
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: build/reports/**
        failOnStandardError: 'true'