trigger:
- master

jobs:
- job: Code_Quality
  pool:
    vmImage: 'Ubuntu 16.04'
  container: norionomura/swiftlint:swift-4.2.1
  timeoutInMinutes: 5
  steps:
  - script: |
      set -o pipefail
      swiftlint lint --strict
    displayName: 'swift lint'
  
- job: SPM_Tests
  dependsOn: Code_Quality
  pool:
    vmImage: 'Ubuntu-16.04'
  container: swift:4.2.1
  timeoutInMinutes: 5
  steps:
  - script: |
      set -o pipefail
      swift test --parallel
    displayName: 'swift test'
