jobs:
- job: swiftlint
  pool:
    vmImage: 'Ubuntu 16.04'
  container: norionomura/swiftlint:swift-4.2.1
  steps:
    - script: |
        set -o pipefail
        mkdir -p build/reports/
        swiftlint lint --strict
      displayName: swiftlint